export enum ControlTypeEnum {
  Checkbox = 'Checkbox',
  Currency = 'Currency',
  DatePicker = 'DatePicker',
  DateTimePicker = 'DateTimePicker',
  Decimal = 'Decimal',
  Dropdown = 'Dropdown',
  Email = 'Email',
  InputSwitch = 'InputSwitch',
  Integer = 'Integer',
  MaskedTextbox = 'MaskedTextbox',
  MultiSelect = 'MultiSelect',
  Password = 'Password',
  PhoneNumber = 'PhoneNumber',
  RadioButton = 'RadioButton',
  SelectButton = 'SelectButton',
  TextArea = 'TextArea',
  Textbox = 'Textbox',
  TimePicker = 'TimePicker',
}
